# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28d1826e418f5339afec1d2573f3848acd857fe64f84bdc835d73739b97645d0a31c89a744f2d00405e66a04c3f60d27256a1eee2ed4ea55e32e1279fa9b3a0b

test:
  secret_key_base: a0b35d94f737631b619f49d89996e4c16762ac115979ccc21baf710e0759a357e5712eca4df6bc1bc688dacd370a7e30e5f99b53a55ca2cad21095a2225cb452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
